feat: add jebtains ai to readme.md
sourcegraph/awesome-code-ai pull request #33
Opened 2024-04-13 12:53 UTC by origamium

2024-04-15 21:57 UTC, jdorfman requested changes
Looks good, just fix the B and I'll merge it :)

2024-04-15 21:57 UTC, jdorfman commented on README.md
> +- [Jetbrains AI](https://www.jetbrains.com/ai/)
Should be "Jet**B**rains"

2024-04-16 06:07 UTC, origamium commented on README.md
> +- [Jetbrains AI](https://www.jetbrains.com/ai/)
Ok. I fixed that.

2024-04-19 13:53 UTC, jdorfman approved these changes
Thank you!

2024-04-19 13:53 UTC, merged